sudo: required
services:
 - docker

before_install:
 - docker build -t abhi25591/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true abhi25591/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-1-343948227382"
 bucket_path: "docker-react"
 on:
  branch: master
access_key_id:
 secure: $AWS_ACCESS_KEY
secret_access_key
 secure: $AWS_SECRET_KEY

