version: '3'
services:
  web:
    build:
      context: C:\Users\abhispandey\client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - //c/Users/abhispandey/client:/usr/app